### ISSUE TITLE
README code does not work for using existing typings

### ISSUE THREAD

**Issue by dsevillamartin** [flarum/flarum-tsconfig#1]
![image](https://user-images.githubusercontent.com/6401250/120555298-e05d0480-c3c8-11eb-939c-c2dabbb44e38.png)

At least PhpStorm does not resolve typings because the `baseUrl` property isn't set. Setting it allows them to work.

![image](https://user-images.githubusercontent.com/6401250/120555345-efdc4d80-c3c8-11eb-8611-9b262e6f1b00.png)

**Comment by davwheat** [comment]
Hmm this is a weird one...

I haven't run into any issues with this in VS Code so far, but that might be because of the way the typings work or something similar.

I think we can safely add the `baseUrl` to the suggested config.
