### ISSUE TITLE
Issues with IntelliSense in VS Code

### ISSUE THREAD

**Issue by iPurpl3x** [flarum/flarum-tsconfig#4]
I have 2 issues that make this package more or less unusable for me.

I am using VS Code, all packages are up to date.

### My config:

```json
{
    "extends": "flarum-tsconfig",
    "include": ["src/**/*"],
    "compilerOptions": {
        "declarationDir": "./dist-typings",
        "baseUrl": ".",
        "paths": {
            "flarum/*": ["../vendor/flarum/core/js/dist-typings/*"]
        }
    }
}
```

### Problems:

- I cannot automatically import modules from my `src` folder: VS Code generates something like `... from 'src/forum/components/MyComp';` instead of `... from '../components/MyComp';`<br/>
Here I found out that disabling `"baseUrl": ".",` (just commenting it) solves that issue.<br/>

- VS Code doesn't recognize modules from `node_modules` anymore.<br/>
Looking into the details of `flarum-tsconfig`, I found out that setting `"allowJs": false,` makes the node modules work again but making that change breaks auto imports from flarum modules...

**Comment by dsevillamartin** [comment]
I don't see why setting allow js to false would make node modules not work... that seems like the opposite of what should happen? 🤔

**Comment by iPurpl3x** [comment]
@datitisev Actually I did some deeper testing. Some node_modules work and some don't...

These are my dependencies (well there are more but those are relevant in this example)
```json
{
    "autobind-decorator": "^2.4.0",
    "lodash.get": "^4.4.2"
}
```

### When `"allowJs": false,` :
I can import both of those packages
### When `// "allowJs": false,` (commented) :
I can automatically `import autobind from 'autobind-decorator';`

but not `import get from 'lodash.get';`

**Comment by dsevillamartin** [comment]
@iPurpl3x That's probably because `autobind-decorator` includes typings and `lodash.get` has typings in an external pkg (`@types/lodash.get`)

**Comment by iPurpl3x** [comment]
Ah thanks, I didn't know that you may have to install typing libraries for certain npm packages...

**Comment by iPurpl3x** [comment]
But now there is still this thing of the `"baseUrl": ".",`. What is the correct way to manage this ?

**Comment by askvortsov1** [comment]
@davwheat as a fellow vscode user, and seeing that you wrote a lot of this stuff, any ideas?
